const colorCycle = ["lavender", "peach", "lime"];

export function buildCoursePrompt({ topic, materialText, level, duration, goal }) {
  const source = materialText
    ? `Use these uploaded study materials as the main source:\n${materialText.slice(0, 26000)}`
    : `Build the course from this topic: ${topic}`;

  return `
You are CorAI, an AI course builder. Create a practical, student-friendly course.

Preferences:
- Level: ${level}
- Study duration: ${duration}
- Goal: ${goal}
- Topic: ${topic || "derived from uploaded materials"}

${source}

Return only valid JSON with this exact shape:
{
  "title": "Course title",
  "description": "One sentence description",
  "estimatedTime": "4 weeks",
  "learningOutcomes": ["outcome"],
  "modules": [
    {
      "title": "Module title",
      "summary": "Short summary",
      "explanation": "Clear teaching explanation in 1-3 paragraphs",
      "keyConcepts": ["concept"],
      "examples": ["example"],
      "practiceTasks": ["task"],
      "estimatedMinutes": 35,
      "quiz": {
        "title": "Quiz title",
        "questions": [
          {
            "prompt": "Question",
            "options": ["A", "B", "C", "D"],
            "correctOptionIndex": 0,
            "explanation": "Why the answer is correct",
            "topic": "Weak-topic label"
          }
        ]
      }
    }
  ]
}

Rules:
- Create 4 to 7 modules.
- Create exactly 5 quiz questions per module.
- Every question must have exactly 4 options and a zero-based correctOptionIndex.
- Keep content concise enough for a hackfest demo, but useful enough to study from.
`;
}

export function fallbackCourse({ topic, materialText, level, duration, goal }) {
  const inferredTitle = topic?.trim() || inferTitle(materialText) || "Generated Learning Path";
  const concepts = pickConcepts(inferredTitle, materialText);

  return normalizeCourse({
    title: inferredTitle,
    description: `A focused ${level.toLowerCase()} course for ${goal.toLowerCase()}.`,
    estimatedTime: duration,
    learningOutcomes: [
      `Explain the core ideas behind ${inferredTitle}.`,
      "Apply the main concepts through guided practice.",
      "Check understanding with short quizzes.",
      "Identify weak topics for review.",
    ],
    modules: concepts.slice(0, 5).map((concept, index) => ({
      title: concept,
      summary: `Learn the essentials of ${concept}.`,
      explanation: `${concept} is an important part of ${inferredTitle}. Study the definition, common patterns, and practical examples before moving to the quiz.`,
      keyConcepts: [concept, "Definition", "Use cases", "Common mistakes"],
      examples: [`Example: describe how ${concept.toLowerCase()} appears in a real study or exam question.`],
      practiceTasks: [`Write a short explanation of ${concept.toLowerCase()} and create one example question.`],
      estimatedMinutes: 30 + index * 5,
      quiz: {
        title: `${concept} Check`,
        questions: Array.from({ length: 5 }, (_, questionIndex) => ({
          prompt: `Which statement best describes ${concept}?`,
          options: [
            `${concept} is a core concept in this course.`,
            `${concept} is unrelated to the course.`,
            `${concept} only means memorizing terms.`,
            `${concept} cannot be practiced.`,
          ],
          correctOptionIndex: 0,
          explanation: `${concept} is part of the generated learning path and should be understood through examples.`,
          topic: concept,
        })),
      },
    })),
  });
}

export function normalizeCourse(course) {
  const modules = Array.isArray(course?.modules) ? course.modules : [];

  return {
    title: asText(course?.title, "Generated Course"),
    description: asText(course?.description, "A personalized course generated by CorAI."),
    estimatedTime: asText(course?.estimatedTime, "4 weeks"),
    learningOutcomes: asArray(course?.learningOutcomes).slice(0, 8),
    modules: modules.slice(0, 8).map((module, index) => normalizeModule(module, index)),
  };
}

export function cardColorFor(index) {
  return colorCycle[index % colorCycle.length];
}

function normalizeModule(module, index) {
  const title = asText(module?.title, `Module ${index + 1}`);
  const questions = asArray(module?.quiz?.questions)
    .slice(0, 5)
    .map((question, questionIndex) => normalizeQuestion(question, questionIndex, title));

  while (questions.length < 5) {
    questions.push(normalizeQuestion({}, questions.length, title));
  }

  return {
    title,
    summary: asText(module?.summary, `Learn ${title}.`),
    explanation: asText(module?.explanation, `This module explains ${title} with concise examples and practice.`),
    keyConcepts: asArray(module?.keyConcepts).slice(0, 8),
    examples: asArray(module?.examples).slice(0, 5),
    practiceTasks: asArray(module?.practiceTasks).slice(0, 5),
    estimatedMinutes: clampNumber(module?.estimatedMinutes, 15, 120, 35),
    quiz: {
      title: asText(module?.quiz?.title, `${title} Quiz`),
      questions,
    },
  };
}

function normalizeQuestion(question, index, topic) {
  const options = asArray(question?.options).slice(0, 4);
  while (options.length < 4) {
    options.push(`Option ${options.length + 1}`);
  }

  const correctOptionIndex = clampNumber(question?.correctOptionIndex, 0, 3, 0);

  return {
    prompt: asText(question?.prompt, `Question ${index + 1} about ${topic}`),
    options,
    correctOptionIndex,
    explanation: asText(question?.explanation, "Review the related lesson section for the explanation."),
    topic: asText(question?.topic, topic),
  };
}

function asText(value, fallback) {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function asArray(value) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.map((item) => (typeof item === "string" ? item.trim() : "")).filter(Boolean);
}

function clampNumber(value, min, max, fallback) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }

  return Math.min(max, Math.max(min, Math.round(parsed)));
}

function inferTitle(text = "") {
  const words = text
    .split(/\s+/)
    .filter((word) => /^[A-Za-z][A-Za-z-]{3,}$/.test(word))
    .slice(0, 4);

  return words.length ? words.join(" ") : "";
}

function pickConcepts(title, materialText = "") {
  const candidates = [
    ...title.split(/\s+/),
    ...materialText
      .split(/[.\n]/)
      .flatMap((line) => line.split(/\s+/).slice(0, 3)),
  ]
    .map((word) => word.replace(/[^A-Za-z0-9 -]/g, "").trim())
    .filter((word) => word.length > 4);

  const unique = [...new Set(candidates)].slice(0, 5);
  return unique.length >= 4 ? unique : ["Foundations", "Core Concepts", "Worked Examples", "Practice", "Review"];
}
